---
title: "section_4"
author: "patrick Junghenn"
date: "11/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(readxl)
install.packages('tidyr')
library(tidyr)
donations <- read_excel("~/Documents/GitHub/NearestNeighbors-main/UniversityDonations.xls")
head(donations)
str(donations)



# Preprocessing

# - Convert data types 
donations$City <- as.factor(donations$City)
donations$Allocation_Subcategory <- as.factor(donations$Allocation_Subcategory)
donations$College <- as.factor(donations$College)
donations$Gift_Allocation <- as.factor(donations$Gift_Allocation)
donations$Major <- as.factor(donations$Major)
donations$State <- as.factor(donations$State)
donations$Year <- as.factor(donations$Year)
str(donations)

# - Check for missing values
sum(is.na(donations))

# - Drop id column
donations <- subset(donations, select = -c(8))
str(donations)

# Outliers
library(ezids)
donations <- outlierKD2(donations, donations$Amount, rm=TRUE)
donations <- data.frame(donations)
# Hypothesis testing

# ANOVA (only one numeric variable, 'amount', so cant use two sided t tests)
anova_all <- aov(log10(Amount) ~ Gift_Allocation + Allocation_Subcategory + City +
                   College + Year + Major + State, data = donations)
summary.aov(anova_all)
#     ANOVA reveals that significant variables are year and major. All other variables appear to be
#     quite insignificant.

# ChiSquare
# - Major vs Year
table(donations$City, donations$Year)
major_v_year_chi <- chisq.test(donations$City, donations$Year)
major_v_year_chi
#   -Major and year, the only statistically significant variables, are independent




```

